// import { Outfit } from "next/font/google";
// import "./globals.css";

// //components
// import Header from '@/components/Header';
// import Footer from '@/components/Footer';
// //themeprovider
// import { ThemeProvider } from "@/components/ThemeProvider";

// const Outfit = Outfit({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body className={Outfit.className}>
//         <ThemeProvider attribute='class' defaulttheme='light'>
//         <Header/>
//         {children}
//         <Footer/>
//         </ThemeProvider>
//         </body>
//     </html>
//   );
// }


import { Outfit as OutfitFont } from "next/font/google";
import "./globals.css";

//components
import Header from '@/components/Header';
import Footer from '@/components/Footer';
//themeprovider
import { ThemeProvider } from "@/components/ThemeProvider";

const outfitFont = OutfitFont({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={outfitFont.className}>
        <ThemeProvider attribute='class' defaultTheme='light'>
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
